export const filtersActionTypes = {
  FETCH_FILTERS_START: "FETCH_FILTERS_START",
  FETCH_FILTERS_SUCCESS: "FETCH_FILTERS_SUCCESS",
  FETCH_FILTERS_FAILURE: "FETCH_FILTERS_FAILURE",
  ADD_FILTER: "ADD_FILTER",
  REMOVE_FILTER: "REMOVE_FILTER",
};
