export const DUMMY_RESULT = [
  {
    party: "ימינה",
    office_phone: 3242,
    head_office_name: "sdas",
    party_role: "ראש סיעה",
    last_name: "elbaz",
    head_office_phone: 231,
    knesset_role: "ראש ממשלה",
    political_consultant_phone: 2312,
    member_id: 1,
    email: " gil@",
    personal_phone: 555,
    speaker_phone: 2321,
    political_consultant_name: "sdas",
    first_name: "gil",
    position: "coalition",
    speaker_name: "jorge",
    additional_role: "commitee",
    gov_role: "ראש ממשלה",
    picture: "sdas",
  },
  {
    party: "ימינה",
    office_phone: 3242,
    head_office_name: "sdas",
    party_role: "סגן ראש סיעה",
    last_name: "pearlman",
    head_office_phone: 231,
    knesset_role: "סגן ראש ממשלה",
    political_consultant_phone: 2312,
    member_id: 2,
    email: " gil@",
    personal_phone: 555,
    speaker_phone: 2321,
    political_consultant_name: "sdas",
    first_name: "kobi",
    position: "coalition",
    speaker_name: "jorge",
    additional_role: "commitee",
    gov_role: "שר הכלכלה",
    picture: "sdas",
  },
  {
    party: "ליכוד",
    office_phone: 3242,
    head_office_name: "sdas",
    party_role: "ראש סיעה",
    last_name: "by",
    head_office_phone: 231,
    knesset_role: "knesset_role",
    political_consultant_phone: 2312,
    member_id: 3,
    email: " gil@",
    personal_phone: 555,
    speaker_phone: 2321,
    political_consultant_name: "sdas",
    first_name: "tomer",
    position: "coalition",
    speaker_name: "jorge",
    additional_role: "commitee",
    gov_role: "שר הבטחון",
    picture: "sdas",
  },
  {
    party: "Something123",
    office_phone: 3242,
    head_office_name: "sdas",
    party_role: "party_role",
    last_name: "fr",
    head_office_phone: 231,
    knesset_role: "knesset_role",
    political_consultant_phone: 2312,
    member_id: 4,
    email: " gil@",
    personal_phone: 555,
    speaker_phone: 2321,
    political_consultant_name: "sdas",
    first_name: "adi",
    position: "coalition",
    speaker_name: "jorge",
    additional_role: "commitee",
    gov_role: "Head of..",
    picture: "sdas",
  },
  {
    party: "Something123",
    office_phone: 3242,
    head_office_name: "sdas",
    party_role: "party_role",
    last_name: "fr",
    head_office_phone: 231,
    knesset_role: "knesset_role",
    political_consultant_phone: 2312,
    member_id: 5,
    email: " gil@",
    personal_phone: 555,
    speaker_phone: 2321,
    political_consultant_name: "sdas",
    first_name: "adi",
    position: "coalition",
    speaker_name: "jorge",
    additional_role: "commitee",
    gov_role: "Head of..",
    picture: "sdas",
  },
  {
    party: "Something123",
    office_phone: 3242,
    head_office_name: "sdas",
    party_role: "party_role",
    last_name: "fr",
    head_office_phone: 231,
    knesset_role: "knesset_role",
    political_consultant_phone: 2312,
    member_id: 6,
    email: " gil@",
    personal_phone: 555,
    speaker_phone: 2321,
    political_consultant_name: "sdas",
    first_name: "adi",
    position: "coalition",
    speaker_name: "jorge",
    additional_role: "commitee",
    gov_role: "Head of..",
    picture: "sdas",
  },
  {
    party: "Something123",
    office_phone: 3242,
    head_office_name: "sdas",
    party_role: "party_role",
    last_name: "fr",
    head_office_phone: 231,
    knesset_role: "knesset_role",
    political_consultant_phone: 2312,
    member_id: 7,
    email: " gil@",
    personal_phone: 555,
    speaker_phone: 2321,
    political_consultant_name: "sdas",
    first_name: "adi",
    position: "coalition",
    speaker_name: "jorge",
    additional_role: "commitee",
    gov_role: "Head of..",
    picture: "sdas",
  },
  {
    party: "Something123",
    office_phone: 3242,
    head_office_name: "sdas",
    party_role: "party_role",
    last_name: "fr",
    head_office_phone: 231,
    knesset_role: "knesset_role",
    political_consultant_phone: 2312,
    member_id: 8,
    email: " gil@",
    personal_phone: 555,
    speaker_phone: 2321,
    political_consultant_name: "sdas",
    first_name: "adi",
    position: "coalition",
    speaker_name: "jorge",
    additional_role: "commitee",
    gov_role: "Head of..",
    picture: "sdas",
  },
];
